$(document).ready(function () {
    // las animaciones de la pagina "home" estaran aca
  const descripciones = {
    "Arquitectura de computadores": "FUNDAMENTOS BÁSICOS DE LA ORGANIZACIÓN DE UN COMPUTADOR, Y FUNCIONAMIENTO INTERNO. MICROPROCESADORES. MICROINSTRUCCIONES. UNIDADES. CÓDIGOS. DETECCIÓN Y AUTOCORRECCIÓN DE ERRORES. CANALES DE E/S. SEÑALES ANALÓGICAS Y DIGITALES. CIRCUITOS SECUENCIALES Y COMBINACIONALES. ESTRUCTURA INTERNA DE LOS MICROPROCESADORES. MICROINSTRUCCIONES Y MICROCÓDIGO. CONTROLADORES DE 'BUSES'. INTERRUPCIONES. MAPAS DE MEMORIA Y DE E/S. LENGUAJE ENSAMBLADOR. LA PILA DEL SISTEMA. ARQUITECTURA INTEL. MÁQUINAS RISC. COMPUTADORES VECTORIALES Y ESCALARES. ARQUITECTURAS EN PARALELO.",
    
    "Sistemas de informacion 1": "CONCEPTOS BÁSICOS DE: EMPRESA, ORGANIZACIÓN Y DIRECCIÓN. FUNCIONES DE LA ADMINISTRACIÓN. PROCESOS BÁSICOS DE UNA EMPRESA. CONTROL INTERNO. HERRAMIENTAS DE MODELADO DE PROCESOS. RELACIÓN ENTRE PROCESOS Y SISTEMAS. SISTEMAS DE GESTIÓN EMPRESARIAL (ERP / CRM / SCM). PROCESO DE DESARROLLO DE SOFTWARE. CUERPO DE CONOCIMIENTOS DE LA INGENIERÍA DE SOFTWARE.",
    
    "Fundamentos de informatica": "DESCRIPCIÓN FUNCIONAL DE UN COMPUTADOR. CONCEPTO DE PROGRAMA Y DE DATO. SISTEMAS OPERATIVOS. COMPILADORES E INTÉRPRETES. OPERACIONES CON DATOS. CONCEPTO DE ALGORITMO Y SUB-ALGORITMOS. ESTRUCTURAS DE DECISIÓN. ESTRUCTURAS ITERATIVAS. ARREGLOS. OPERACIONES CON VECTORES Y MATRICES.",
    
    "Marketing": "EVOLUCIÓN DEL MARKETING. ROL, ESTRUCTURA Y PROCESOS DE MARKETING DESDE EL PUNTO DE VISTA DE LA EMPRESA, LA ECONOMÍA Y LA SOCIEDAD. MACROENTORNO Y MICROENTORNO. ORIENTACIÓN AL MERCADO. VALOR AL CLIENTE. COMPORTAMIENTO DEL CONSUMIDOR. SISTEMAS DE INFORMACIÓN DE MARKETING TRADICIONAL Y EN INTERNET. INVESTIGACIÓN DE MERCADO. INTELIGENCIA DE MERCADO. SEGMENTACIÓN. POSICIONAMIENTO. ESTRATEGIAS DE MARKETING. PRODUCTO. SERVICIO. CANALES DE DISTRIBUCIÓN. PRECIO. COMUNICACIONES INTEGRADAS DE MARKETING. ORGANIZACIÓN Y MEDICIÓN DEL DESEMPEÑO. RESPONSABILIDAD SOCIAL. PLAN DE MARKETING. ÉTICA EN EL MARKETING.",
    
    "Diseño y desarrollo web": "CONCEPTO: RED INFORMÁTICA MUNDIAL (WORLD WIDE WEB); PÁGINA WEB; NAVEGADOR WEB; SERVIDOR WEB. LENGUAJES WEB. EL DISEÑO WEB: CONCEPTOS; EL PROCESO DE DISEÑO; PROTOTIPADO; TÉCNICAS DE MAQUETADO; HERRAMIENTAS. EL PROCESO DE VALIDACIÓN DEL DISEÑO. CONCEPTOS DE USABILIDAD Y EXPERIENCIA DE USUARIO. DESARROLLO DE INTERFACES DE USUARIO: CONCEPTOS; EL PROCESO DE DESARROLLO. COMPRENSIÓN Y UTILIZACIÓN DE TECNOLOGÍAS COMO: HTML (HYPERTEXT MARKUP LANGUAGE); CSS3 (CASCADING STYE SHEETS); DOM (DOCUMENT OBJECT MODEL); JAVASCRIPT. EVENTOS: TIPOS; GESTIÓN Y MANEJO DE EVENTOS. OBTENCIÓN, GESTIÓN Y MANTENIMIENTO DE DOMINIO Y HOSTING. DESPLIEGUE DE PRODUCTO."
  };

  $("tbody tr").click(function () {
    const nombreMateria = $(this).find("td:first").text();
    const descripcion = descripciones[nombreMateria] || "Descripción no disponible.";

    $("#modalMateriaLabel").text(nombreMateria);
    $("#modalDescripcion").text(descripcion);

    const modal = new bootstrap.Modal(document.getElementById('modalMateria'));
    modal.show();
  });
});